language: python

env:
  - DJANGO_SETTINGS_MODULE=fruitmarket.settings.ci

cache: pip

python:
  - 3.5
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run manage.py test

after_success:
  - coveralls
