# Generated by Django 2.0.4 on 2018-05-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitsales',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='amount'),
        ),
    ]
